/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.awt.Color;

/**
 *
 * @author Ninbus
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPantalla = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaCinta = new javax.swing.JTextArea();
        ComboBoxColores = new javax.swing.JComboBox<>();
        btnMR = new javax.swing.JButton();
        btnMC = new javax.swing.JButton();
        btnMU = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCreadores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setLocation(new java.awt.Point(350, 150));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtPantalla.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        TextAreaCinta.setColumns(20);
        TextAreaCinta.setRows(5);
        jScrollPane1.setViewportView(TextAreaCinta);

        ComboBoxColores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Color Blanco", "Color Negro", "Color Verde", "Color Amarillo" }));
        ComboBoxColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxColoresActionPerformed(evt);
            }
        });

        btnMR.setBackground(new java.awt.Color(255, 255, 255));
        btnMR.setText("MR");

        btnMC.setBackground(new java.awt.Color(255, 255, 255));
        btnMC.setText("MC");

        btnMU.setBackground(new java.awt.Color(255, 255, 255));
        btnMU.setText("MU");

        btnCE.setBackground(new java.awt.Color(255, 255, 255));
        btnCE.setText("CE");

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnDivision.setBackground(new java.awt.Color(255, 255, 255));
        btnDivision.setText("/");

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnMulti.setBackground(new java.awt.Color(255, 255, 255));
        btnMulti.setText("X");

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(255, 255, 255));
        btnMenos.setText("-");

        btn0.setBackground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPunto.setBackground(new java.awt.Color(255, 255, 255));
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");

        btnSuma.setBackground(new java.awt.Color(255, 255, 255));
        btnSuma.setText("+");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.jpg"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCreadores.setBackground(new java.awt.Color(255, 255, 255));
        btnCreadores.setText("Creadores");
        btnCreadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPantalla)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMU, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxColores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMU, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBoxColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCreadores, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxColoresActionPerformed
        String eleccion = ComboBoxColores.getSelectedItem().toString();
        if(eleccion.equalsIgnoreCase("Color Blanco")){
            //Seteamos color del Panel
            jPanel1.setBackground(Color.white);
            //Seteamos color del Combobox
            ComboBoxColores.setBackground(Color.white);
            //Seteamos color de letra de botones
            btnMR.setForeground(Color.black);btnMC.setForeground(Color.black);
            btnMU.setForeground(Color.black);btnCE.setForeground(Color.black);
            btnPunto.setForeground(Color.black);btnIgual.setForeground(Color.black);
            btnDivision.setForeground(Color.black);btnMulti.setForeground(Color.black);
            btnMenos.setForeground(Color.black);btnSuma.setForeground(Color.black);
            btn0.setForeground(Color.black);btn1.setForeground(Color.black);
            btn2.setForeground(Color.black);btn3.setForeground(Color.black);
            btn4.setForeground(Color.black);btn5.setForeground(Color.black);
            btn6.setForeground(Color.black);btn7.setForeground(Color.black);
            btn8.setForeground(Color.black);btn9.setForeground(Color.black);
            //Seteamos color de fondo botones
            btnMR.setBackground(Color.white);btnMC.setBackground(Color.white);
            btnMU.setBackground(Color.white);btnCE.setBackground(Color.white);
            btnPunto.setBackground(Color.white);btnIgual.setBackground(Color.white);
            btnDivision.setBackground(Color.white);btnMulti.setBackground(Color.white);
            btnMenos.setBackground(Color.white);btnSuma.setBackground(Color.white);
            btn0.setBackground(Color.white);btn1.setBackground(Color.white);
            btn2.setBackground(Color.white);btn3.setBackground(Color.white);
            btn4.setBackground(Color.white);btn5.setBackground(Color.white);
            btn6.setBackground(Color.white);btn7.setBackground(Color.white);
            btn8.setBackground(Color.white);btn9.setBackground(Color.white);
            //Seteamos color del boton Creadores
            btnCreadores.setBackground(Color.white);
            btnCreadores.setForeground(Color.black);
            
        }else if(eleccion.equalsIgnoreCase("Color Negro")){
            //Seteamos color del Panel
            jPanel1.setBackground(Color.black);
            //Seteamos color del Combobox
            ComboBoxColores.setBackground(Color.DARK_GRAY);
            //Seteamos color de letra de botones
            btnMR.setForeground(Color.white);btnMC.setForeground(Color.white);
            btnMU.setForeground(Color.white);btnCE.setForeground(Color.white);
            btnPunto.setForeground(Color.white);btnIgual.setForeground(Color.white);
            btnDivision.setForeground(Color.white);btnMulti.setForeground(Color.white);
            btnMenos.setForeground(Color.white);btnSuma.setForeground(Color.white);
            btn0.setForeground(Color.white);btn1.setForeground(Color.white);
            btn2.setForeground(Color.white);btn3.setForeground(Color.white);
            btn4.setForeground(Color.white);btn5.setForeground(Color.white);
            btn6.setForeground(Color.white);btn7.setForeground(Color.white);
            btn8.setForeground(Color.white);btn9.setForeground(Color.white);
            //Seteamos color de fondo botones
            btnMR.setBackground(Color.DARK_GRAY);btnMC.setBackground(Color.DARK_GRAY);
            btnMU.setBackground(Color.DARK_GRAY);btnCE.setBackground(Color.DARK_GRAY);
            btnPunto.setBackground(Color.DARK_GRAY);btnIgual.setBackground(Color.DARK_GRAY);
            btnDivision.setBackground(Color.DARK_GRAY);btnMulti.setBackground(Color.DARK_GRAY);
            btnMenos.setBackground(Color.DARK_GRAY);btnSuma.setBackground(Color.DARK_GRAY);
            btn0.setBackground(Color.DARK_GRAY);btn1.setBackground(Color.DARK_GRAY);
            btn2.setBackground(Color.DARK_GRAY);btn3.setBackground(Color.DARK_GRAY);
            btn4.setBackground(Color.DARK_GRAY);btn5.setBackground(Color.DARK_GRAY);
            btn6.setBackground(Color.DARK_GRAY);btn7.setBackground(Color.DARK_GRAY);
            btn8.setBackground(Color.DARK_GRAY);btn9.setBackground(Color.DARK_GRAY);
            //Seteamos color del boton Creadores
            btnCreadores.setBackground(Color.DARK_GRAY);
            btnCreadores.setForeground(Color.white);
            
        }else if(eleccion.equalsIgnoreCase("Color Verde")){
            //Seteamos color del Panel
            jPanel1.setBackground(Color.green);
            //Seteamos color del Combobox
            ComboBoxColores.setBackground(Color.orange);
            //Seteamos color de letra de botones
            btnMR.setForeground(Color.blue);btnMC.setForeground(Color.blue);
            btnMU.setForeground(Color.blue);btnCE.setForeground(Color.blue);
            btnPunto.setForeground(Color.blue);btnIgual.setForeground(Color.blue);
            btnDivision.setForeground(Color.blue);btnMulti.setForeground(Color.blue);
            btnMenos.setForeground(Color.blue);btnSuma.setForeground(Color.blue);
            btn0.setForeground(Color.blue);btn1.setForeground(Color.blue);
            btn2.setForeground(Color.blue);btn3.setForeground(Color.blue);
            btn4.setForeground(Color.blue);btn5.setForeground(Color.blue);
            btn6.setForeground(Color.blue);btn7.setForeground(Color.blue);
            btn8.setForeground(Color.blue);btn9.setForeground(Color.blue);
            //Seteamos color de fondo botones
            btnMR.setBackground(Color.orange);btnMC.setBackground(Color.orange);
            btnMU.setBackground(Color.orange);btnCE.setBackground(Color.orange);
            btnPunto.setBackground(Color.orange);btnIgual.setBackground(Color.orange);
            btnDivision.setBackground(Color.orange);btnMulti.setBackground(Color.orange);
            btnMenos.setBackground(Color.orange);btnSuma.setBackground(Color.orange);
            btn0.setBackground(Color.orange);btn1.setBackground(Color.orange);
            btn2.setBackground(Color.orange);btn3.setBackground(Color.orange);
            btn4.setBackground(Color.orange);btn5.setBackground(Color.orange);
            btn6.setBackground(Color.orange);btn7.setBackground(Color.orange);
            btn8.setBackground(Color.orange);btn9.setBackground(Color.orange); 
            //Seteamos color del boton Creadores
            btnCreadores.setBackground(Color.orange);
            btnCreadores.setForeground(Color.blue);
            
        }else if(eleccion.equalsIgnoreCase("Color Amarillo")){
            //Seteamos color del Panel
            jPanel1.setBackground(Color.yellow);
            //Seteamos color del Combobox
            ComboBoxColores.setBackground(Color.blue);
            //Seteamos color de letra de botones
            btnMR.setForeground(Color.white);btnMC.setForeground(Color.white);
            btnMU.setForeground(Color.white);btnCE.setForeground(Color.white);
            btnPunto.setForeground(Color.white);btnIgual.setForeground(Color.white);
            btnDivision.setForeground(Color.white);btnMulti.setForeground(Color.white);
            btnMenos.setForeground(Color.white);btnSuma.setForeground(Color.white);
            btn0.setForeground(Color.white);btn1.setForeground(Color.white);
            btn2.setForeground(Color.white);btn3.setForeground(Color.white);
            btn4.setForeground(Color.white);btn5.setForeground(Color.white);
            btn6.setForeground(Color.white);btn7.setForeground(Color.white);
            btn8.setForeground(Color.white);btn9.setForeground(Color.white);
            //Seteamos color de fondo botones
            btnMR.setBackground(Color.blue);btnMC.setBackground(Color.blue);
            btnMU.setBackground(Color.blue);btnCE.setBackground(Color.blue);
            btnPunto.setBackground(Color.blue);btnIgual.setBackground(Color.blue);
            btnDivision.setBackground(Color.blue);btnMulti.setBackground(Color.blue);
            btnMenos.setBackground(Color.blue);btnSuma.setBackground(Color.blue);
            btn0.setBackground(Color.blue);btn1.setBackground(Color.blue);
            btn2.setBackground(Color.blue);btn3.setBackground(Color.blue);
            btn4.setBackground(Color.blue);btn5.setBackground(Color.blue);
            btn6.setBackground(Color.blue);btn7.setBackground(Color.blue);
            btn8.setBackground(Color.blue);btn9.setBackground(Color.blue);
            //Seteamos color del boton Creadores
            btnCreadores.setBackground(Color.blue);
            btnCreadores.setForeground(Color.white);
            
            //Creadores abrir = new Creadores();  //instancia el form 
            //abrir.jPanel1.setBackground(Color.yellow);
        }
    }//GEN-LAST:event_ComboBoxColoresActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCreadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreadoresActionPerformed
        String eleccion = ComboBoxColores.getSelectedItem().toString();
        Creadores abrir = new Creadores();  //instancia el form 
        abrir.txtCreadores.setText("Carlos\nJose");
        abrir.setVisible(true);  //abre el form seleccionCampos
        this.dispose(); //Oculta ventana Actual
    }//GEN-LAST:event_btnCreadoresActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPuntoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxColores;
    private javax.swing.JTextArea TextAreaCinta;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCreadores;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMU;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables
}
